# Generated by Django 4.0.4 on 2023-03-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaliTouristDestinatio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('place', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('coordinate', models.CharField(max_length=255)),
                ('rating', models.FloatField()),
                ('reviews_count', models.IntegerField()),
                ('source', models.CharField(max_length=555)),
                ('description', models.CharField(max_length=555)),
                ('fee', models.CharField(max_length=555)),
            ],
        ),
    ]
