# Generated by Django 4.0.4 on 2023-03-03 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_balitouristdestinatio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BaliTouristDestinatio',
            new_name='BaliTouristDestination',
        ),
    ]
